### ISSUE TITLE
ios 15.8.2

### ISSUE THREAD

**Issue by Xqshyg** [doronz88/DeveloperDiskImage#7]
Is there any developer diskimage for ios 15.8?

**Comment by doronz88** [comment]
I don't have one. You're welcome to post your own

**Comment by joonyoungP** [comment]
@Xqshyg 
 ios 15.8 added on this request 
https://github.com/doronz88/DeveloperDiskImage/pull/8 

check if there is an issue

**Comment by doronz88** [comment]
no such issue

**Comment by doronz88** [comment]
Oh it was already added there - that's a PR
